### ISSUE TITLE
Allow keystore password, api username, and api password to be set via environment variables

### ISSUE THREAD

**Issue by preetsethi** [smartcontractkit/chainlink#1414]
### Feature Request
Allow the following configuration inputs to be set via environment variables:
1. keystore password
1. api username
1. api password

### Reasoning for Request
Very specifically to my use case: allowing for these inputs to be read via environment variables would ease my automated deployment process via AWS ECS + AWS Fargate. Specifically, AWS Fargate does not allow you to bootstrap container images with files when using a hosted image.

In the general case: 
[You allow setting many configuration options via environment variables.](https://docs.chain.link/docs/running-a-chainlink-node#section-create-an-environment-file) You should also be able to set the requested credentials via environment variables.

Not asking you to remove the file input method, just asking you also support environment variables.

**EDIT**: wanted to provide additional information regarding the specificity of my issue
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data.html

No where does AWS recommend injecting secrets via the filesystem.
Fundamentally, I think this is a problem.

My specific goal is to eventually get a failover ready, load-balanced Chainlink cluster running on AWS ECS via AWS Fargate. While I understand that this is vendor specific, I do think this request is supported by a valid case. No managed infrastructure, just pull the official Chainlink docker image, specify the right config and environment variables, and suddenly you have a load balanced cluster of Chainlink nodes running on ECS / Fargate? That sounds like the right blog post for me to write about Chainlink and their open dev community. 

### Questions
Precedence!!! 
If environment variables are set and file inputs are specified, which takes priority?

I would be more than happy to work on this and submit as a pull request, however, would like some input from the team and contributors as I'm obviously a newbie here. Looking forward to responses.

**Comment by se3000** [comment]
Hi @preetsethi, thanks for raising the issue. My understanding is that storing credentials in a file is preferred because users who can read that file can be explicitly limited. Environment variables are easier to leak/print most commonly they can be accessed by child processes. There is precedence with this pattern for blockchain related applications, as bitcoind, geth, and parity each read the password from a file last time I checked.

**Comment by jleeh** [comment]
It's important to note that even if environment variables were supported for the secrets, it still wouldn't work properly with Fargate due to no true horizontal scaling support:

- Failover node doesn't have an open port so the healthchecks would fail causing a reboot loop.
- When performing rolling updates, Fargate would always consider the new node as unhealthy because it wouldn't grab the DB lock and not open the port, blocking rolling updates.
- If you fooled the healthchecks by doing something like running a reverse proxy in NGINX so they're always marked as healthy, when you browse to your node every 1 in 2 requests will be routed to a node that doesn't have the UI up and will fail.

The best way to achieve what you're looking to do is assign instances in an ASG to a ALB and don't have any actions to re-create the instances if they're marked as unhealthy. That way, you can leave unhealthy hosts (waiting for the DB lock) on the load balancer and then you're successfully routed to the failover node when it becomes active.

**Comment by preetsethi** [comment]
@se3000 You're right about bitcoind, geth, and parity; appreciate that detail about precedence.
Also thanks to @thodges-gh: I posted this issue before he was able to answer me on your Gitter.

@jleeh Thanks for sharing your experience with Fargate. I was using the Chainlink node deployment as a fun way to test some new options for container deployment at work. Fargate clearly still has some mighty limitations, namely lack of SELinux support, privileged mode, or container links without port mapping.

Thanks guys, closing this.
