### ISSUE TITLE
CLI job spec creation command can take a file path

### ISSUE THREAD

**Issue by se3000** [smartcontractkit/chainlink#160]
The `chainlink create` CLI command currently accepts JSON. It should optionally accept a file path where it reads the JSON from instead.

We're open to ideas about the exact API, open to suggestions. Ideally any argument that doesn't start with a left curly bracket would be identified as a file path which curl tries to look up and read. The no curly left bracket to start a file name seems like a reasonable assumption(you should probably be starting your paths with `/...`, `./...`, or `~/...` anyway). If there's a problem with that, passing a flag or starting with "@" [like curl does](https://stackoverflow.com/a/9134603/2615087) seems like a good way forward.

Open to feedback.

**Comment by se3000** [comment]
@whatsadebugger you'd expressed some interest in this before. Still interested? Let me know and I'll mark it as in progress.

**Comment by whatsadebugger** [comment]
Yes I have started working on it

On Mar 14, 2018 12:34 AM, "Steve Ellis" <notifications@github.com> wrote:

@whatsadebugger <https://github.com/whatsadebugger> you'd expressed some
interest in this before. Still interested? Let me know and I'll mark it as
in progress.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/smartcontractkit/chainlink/issues/160#issuecomment-372909845>,
or mute the thread

**Comment by se3000** [comment]
Excellent, done.

**Comment by se3000** [comment]
Handled by #162. Thanks!
