### ISSUE TITLE
[NODE] EthTx adapter "succeeds" even if the transaction failed

### ISSUE THREAD

**Issue by samphilipd** [smartcontractkit/chainlink#2182]
EthTx adapter gets marked as successful even if the actual transaction failed (e.g. due to bad call, out of gas, reverted etc).

**Comment by thodges-gh** [comment]
@samphilipd This is the expected behavior. The signing and broadcasting of the transaction itself was successful according to the node. If a consuming contract is purposely set up to revert on fulfillment, that should not be allowed to effect the node's operation. See [MaliciousConsumer.sol](https://github.com/smartcontractkit/chainlink/blob/develop/evm/contracts/tests/MaliciousConsumer.sol#L24-L26) for an example.

**Comment by samphilipd** [comment]
OK makes sense, thanks for the explanation @thodges-gh
