### ISSUE TITLE
[FEAT] Initialize node non-interactively

### ISSUE THREAD

**Issue by jonpurdy** [smartcontractkit/chainlink#2401]
**Description**
When initializing a node for the first time, it requests a Postgres password, and an email/password for node login. I'd like to see a way to pass these in via CLI arguments or read via environment variables so that nodes can be spun up programmatically.

**Motivation**
Using Terraform to spin up and recreate nodes, so being able to fully automate this would be great.

**Justification**
Piping things through via echo or redirection can be a bit flakey and hard to debug if something goes wrong.

**Additional Information**
I see that you can set a PGPASSWORD in the .env file, but that would be used after the initial setup. I also see in the repo /tools/clroot/apicredentials but it looks like this is being used for test cases, unless I'm mistaken.

**Comment by thodges-gh** [comment]
Hi @jonpurdy thanks for the report! Just to clarify, the first password that the node asks for is the keystore password for your Ethereum wallet, not the Postgres database password. These passwords (for the wallet and API) can be specified in text files and supplied to the node upon startup with the `-p` and `-a` flags respectively.

We will not allow these values to be set via environment variables due to security concerns. You can read [this](https://github.com/smartcontractkit/chainlink/issues/1414) previous issue on the subject. We also use Terraform for our infrastructure and one of our engineers has [released](https://github.com/jleeh/chainlink-terraform) an example repo that should help you get started.

**Comment by jonpurdy** [comment]
That's great; looks like all my questions are answered here or in the example Terraform repo!
