### ISSUE TITLE
undefined: common.EmptyHash

### ISSUE THREAD

**Issue by NavyAdmiral** [smartcontractkit/chainlink#422]
I followed instruction steps, but installation failed during `make install`.
![image](https://user-images.githubusercontent.com/40662484/42700026-8e3040ee-86d3-11e8-904f-1641712b2021.png)

### System Information

- Network (Main net, Ropsten, etc.):  Ropsten
- Ethereum client (Geth/Parity) and version: Geth 
- Go version: 1.10
- Host OS: Linux
- Commit (INFO line when starting the node): 84b2e23932b7113390db0abef618e3a996ba0cca

**Comment by thodges-gh** [comment]
Looks like Go-Ethereum removed the `EmptyHash` function.

**Comment by thodges-gh** [comment]
Can you provide the output of `dep version` please?

**Comment by NavyAdmiral** [comment]
@thodges-gh `version : devel`

**Comment by thodges-gh** [comment]
Okay, I can reproduce this if I run `dep ensure -update` and then `make install`. The problem is when you run `dep ensure -update`, it modifies the Gopkg.lock file with a newer version and hash, and we require an older one. Here's what I did to fix:
```bash
git checkout -- Gopkg.lock
make install
```

Try that out and let me know if it fixes it.

**Comment by NavyAdmiral** [comment]
Didn't fix it

**Comment by thodges-gh** [comment]
Can you attach your Gopkg.lock file here, or just a snippit of the "github.com/ethereum/go-ethereum" section including the revision and version?

**Comment by NavyAdmiral** [comment]
[Here](https://pastebin.com/raw/SJ0S5yvw)

**Comment by thodges-gh** [comment]
Alright, this is turning out to be a tough one to actually reproduce since your Gopkg.lock looks fine. What I'm doing is building a new Ubuntu VM, installing Go, NodeJS, Yarn, etc., and then `make install`. You should be able to simulate this without having to start fresh by creating a new directory, and using that as your `GOPATH`.

```bash
mkdir ~/go2
export GOPATH=~/go2
# modify your path here to change /home/$USER/go/bin to /home/$USER/go2/bin
go get -u github.com/golang/dep/cmd/dep
go get -d github.com/smartcontractkit/chainlink
cd $GOPATH/src/github.com/smartcontractkit/chainlink
# you should be at ~/go2/src/github.com/smartcontractkit/chainlink now
make install
```

if that works, then there's something with your existing install that was preventing the correct version of go-ethereum from being used. If it doesn't work, then could you give me the results from running `go env`?

**Comment by NavyAdmiral** [comment]
@thodges-gh that worked, thanks.
