### ISSUE TITLE
choice of send vs transfer in `EthBalanceMonitor`

### ISSUE THREAD

**Issue by jorijnsmit** [smartcontractkit/chainlink#6620]
@Nic0S any reason for the transfer method of choice to differ in these two lines?

what i understand is that `.transfer` actually reverts, which in my mind would make more sense to also implement in the `topUp` method, to make sure keepers do not waste gas by calling `performUpkeep` for a `.send` which will not go through anyway.

https://github.com/smartcontractkit/chainlink/blob/197df9034daec0e1592e2489edbf26f5c1c416af/contracts/src/v0.8/upkeeps/EthBalanceMonitor.sol#L132
https://github.com/smartcontractkit/chainlink/blob/197df9034daec0e1592e2489edbf26f5c1c416af/contracts/src/v0.8/upkeeps/EthBalanceMonitor.sol#L180

**Comment by alexroan** [comment]
Hi! You are correct in that `transfer` reverts.

A revert is not actually desirable in the case you point out (line 132) because the `topUp` function that it's in performs top-ups on an array of addresses (parameter: `address[] memory needsFunding`). If ten addresses are passed to it to be topped up and one reverts, none of the addresses would receive their topup if we use `transfer`. The revert unwinds all state change.

However, using `send` with succeed/fail events as we do instead, a single failed transfer doesn't stop others, and also emits a failure event for a specific address which can help debug the issue.

**Comment by jorijnsmit** [comment]
makes total sense, thanks you for your quick response!
