### ISSUE TITLE
Issue compiling: cannot use tx.GasLimit (type *big.Int) as type uint64 in argument to types.NewTransaction

### ISSUE THREAD

**Issue by recursiev** [smartcontractkit/chainlink#98]
Fired up an AWS AMI instance, installed Go 1.10.
Then,
     $ go get -u github.com/smartcontractkit/chainlink

Immediately see this error:
Projects/src/github.com/smartcontractkit/chainlink/store/models/eth.go:33:5: cannot use tx.GasLimit (type *big.Int) as type uint64 in argument to types.NewTransaction

**Comment by dimroc** [comment]
Thanks for bringing this up @recursiev. While we fix, please try the steps here to get unblocked:
https://github.com/smartcontractkit/chainlink/issues/91#issuecomment-366565878

**Comment by thodges-gh** [comment]
I believe this issue is due to `go get` and `dep ensure` installing different versions of packages. The fix would be to update the README to change all instances of `go get -u github.com/smartcontractkit/chainlink` to a `git clone` command followed by `dep ensure`. Using `go get` would be friendlier for people to come to the project and get started, but `dep ensure` gives us more control over which versions of packages to install.

@recursiev, in the mean time, go ahead and follow the instructions below to get the build going:
- Install Dep with `go get -u github.com/golang/dep/cmd/dep
- Clone the repo into $GOPATH/src/github.com/smartcontractkit/chainlink
- Run `dep ensure` in the chainlink directory
- Build the binary with `go build -o chainlink`

**Comment by se3000** [comment]
@recursiev thanks for pointing this out. It should be fixed now by https://github.com/smartcontractkit/chainlink/pull/99. Please pull and try out the [updated install instructions](https://github.com/smartcontractkit/chainlink/pull/99).
